# Generated by Django 2.2.1 on 2019-05-19 17:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Twice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('birth', models.DateTimeField(default=django.utils.timezone.now)),
                ('nationality', models.CharField(choices=[('KR', '대한민국'), ('JP', '일본'), ('TW', '대만')], max_length=5)),
                ('position', models.TextField()),
            ],
        ),
    ]
